apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cpu-app
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 20 }
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
        - name: cpu-app
          image: k8s.gcr.io/hpa-example
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
